Add azure to valid benchmark schemas
sysdiglabs/terraform-provider-sysdig pull request #125
Opened 2021-09-15 21:48 UTC by aq17

2021-09-15 23:07 UTC, nkraemer-sysdig approved these changes

2021-09-24 07:25 UTC, tembleking requested changes
Am I missing the documentation update here :) 
Other than that, thank you for the contribution!

2021-09-24 22:08 UTC, aq17 commented
> Am I missing the documentation update here :)
> Other than that, thank you for the contribution!

added!

2021-09-27 16:34 UTC, tembleking approved these changes
Thank you! LTGM

2021-09-27 18:18 UTC, merged