feat(onboarding): Datasource for OCI Trusted app group
sysdiglabs/terraform-provider-sysdig pull request #577
Opened 2024-11-27 23:14 UTC by ravinadhruve10

Change summary:
----------------
- Adding new datasource secure_trusted_oracle_app to fetch OCI trusted identity per app group.
- Added acc tests and docs for the new datasource.

2024-12-02 16:59 UTC, haresh-suresh approved these changes

2024-12-02 17:26 UTC, jose-pablo-camacho requested changes

2024-12-02 17:26 UTC, jose-pablo-camacho commented on sysdig/data_source_sysdig_secure_onboarding.go
> +				Type:     schema.TypeString,
We should add the `user_ocid` passed from the onboarding API since that's needed as part of the component service principal metadata

2024-12-02 21:30 UTC, jose-pablo-camacho approved these changes

2024-12-03 21:45 UTC, haresh-suresh approved these changes

2024-12-03 21:54 UTC, merged