feat(secure-vm): implement sysdig_secure_accept_vulnerability_risk resource
sysdiglabs/terraform-provider-sysdig pull request #579
Opened 2024-12-11 01:31 UTC by tembleking

2025-01-03 11:08 UTC, airadier requested changes

2025-01-03 11:08 UTC, airadier commented on website/docs/r/secure_vulnerability_accept_risk.md
> +
Put CVE before rules

```suggestion


### CVE Risk acceptance

```terraform
resource "sysdig_secure_vulnerability_accept_risk" "accept_resource_cve_globally" {
  cve             = "CVE-2021-44228"
  description     = "Accept risk for CVE-2021-44228 globally"
  reason          = "RiskMitigated"
  stages          = ["runtime"]
  expiration_date = "2025-01-02"
}

resource "sysdig_secure_vulnerability_accept_risk" "accept_resource_cve_image_exact" {
  cve             = "CVE-2022-1234"
  image           = "docker.io/library/python:3.9"
  description     = "Accept risk for Python 3.9 image"
  reason          = "RiskOwned"
  stages          = ["pipeline"]
}

resource "sysdig_secure_vulnerability_accept_risk" "accept_resource_cve_image_prefix" {
  cve             = "CVE-2023-4567"
  image           = "docker.io/company/frontend:*"
  description     = "Accept risk for all frontend image versions"
  reason          = "RiskAvoided"
  stages          = ["runtime"]
  expiration_date = "2025-01-02"
}

resource "sysdig_secure_vulnerability_accept_risk" "accept_resource_cve_image_suffix" {
  cve             = "CVE-2020-5678"
  image           = "*:stable"
  description     = "Accept risk for stable tag images"
  reason          = "RiskNotRelevant"
  stages          = []
  expiration_date = "2025-01-02"
}

resource "sysdig_secure_vulnerability_accept_risk" "accept_resource_cve_image_contains" {
  cve             = "CVE-2019-7890"
  image           = "*golang*"
  description     = "Accept risk for Go-based images"
  reason          = "Custom"
  stages          = ["pipeline"]
  expiration_date = "2025-01-02"
}

resource "sysdig_secure_vulnerability_accept_risk" "accept_resource_cve_hostname_exact" {
  cve             = "CVE-2022-8901"
  hostname        = "api-prod-01.mydomain.com"
  description     = "Accept risk for production API server"
  reason          = "RiskTransferred"
  stages          = ["runtime"]
  expiration_date = "2025-01-02"
}

resource "sysdig_secure_vulnerability_accept_risk" "accept_resource_cve_hostname_contains" {
  cve               = "CVE-2021-5678"
  hostname_contains = "cache"
  description       = "Accept risk for cache servers"
  reason            = "RiskMitigated"
  stages            = []
  expiration_date   = "2025-01-02"
}

resource "sysdig_secure_vulnerability_accept_risk" "accept_resource_cve_package" {
  cve             = "CVE-2018-12345"
  package_name    = "openssl"
  description     = "Accept risk for OpenSSL package"
  reason          = "RiskOwned"
  stages          = ["pipeline", "runtime"]
  expiration_date = "2025-01-02"
}

resource "sysdig_secure_vulnerability_accept_risk" "accept_resource_cve_package_and_version" {
  cve             = "CVE-2017-6543"
  package_name    = "glibc"
  package_version = "2.17"
  description     = "Accept risk for glibc 2.17 package"
  reason          = "RiskAvoided"
  stages          = []
  expiration_date = "2025-01-02"
}
```

### Rule risk acceptance

```terraform
resource "sysdig_secure_vulnerability_accept_risk" "accept_resource_rule_globally" {
  rule_id         = 12345
  description     = "Accept risk for rule globally"
  reason          = "Custom"
  stages          = ["pipeline", "runtime"]
  expiration_date = "2025-01-02"
}

resource "sysdig_secure_vulnerability_accept_risk" "accept_resource_rule_image_exact" {
  rule_id         = 12345
  image           = "docker.io/library/mysql:8.0"
  description     = "Accept risk for MySQL 8.0 image"
  reason          = "RiskAvoided"
  stages          = ["pipeline"]
}

resource "sysdig_secure_vulnerability_accept_risk" "accept_resource_rule_image_prefix" {
  rule_id         = 12345
  image           = "docker.io/company/backend:*"
  description     = "Accept risk for backend images"
  reason          = "RiskMitigated"
  stages          = ["runtime"]
  expiration_date = "2025-01-02"
}

resource "sysdig_secure_vulnerability_accept_risk" "accept_resource_rule_image_suffix" {
  rule_id         = 12345
  image           = "*:latest"
  description     = "Accept risk for images tagged as 'latest'"
  reason          = "RiskOwned"
  stages          = []
  expiration_date = "2025-01-02"
}

resource "sysdig_secure_vulnerability_accept_risk" "accept_resource_rule_image_contains" {
  rule_id         = 12345
  image           = "*redis*"
  description     = "Accept risk for Redis images"
  reason          = "RiskNotRelevant"
  stages          = ["pipeline"]
  expiration_date = "2025-01-02"
}

resource "sysdig_secure_vulnerability_accept_risk" "accept_resource_rule_hostname_exact" {
  rule_id         = 12345
  hostname        = "db-prod-01.mydomain.com"
  description     = "Accept risk for production database host"
  reason          = "RiskTransferred"
  stages          = ["runtime"]
  expiration_date = "2025-01-02"
}

resource "sysdig_secure_vulnerability_accept_risk" "accept_resource_rule_hostname_contains" {
  rule_id           = 12345
  hostname_contains = "worker"
  description       = "Accept risk for worker nodes"
  reason            = "Custom"
  stages            = []
  expiration_date   = "2025-01-02"
}
```

```

2025-01-03 11:08 UTC, airadier commented on website/docs/r/secure_vulnerability_accept_risk.md
> +  - **Example**: `"2025-01-02"`
```suggestion
### Required Arguments

#### Context Arguments

-> **Note:** Not all context arguments can be combined freely. Some combinations are valid while others are not. For more information on valid combinations, please refer to the examples provided above. You need to specify at least some context arguments, so they are not completely optional.

- `cve` - The CVE (Common Vulnerabilities and Exposures) identifier for the vulnerability being accepted.
  - **Type**: `string`
  - **Example**: `"CVE-2021-44228"`

- `hostname` - The exact hostname for which the vulnerability risk is being accepted.
  - **Type**: `string`
  - **Example**: `"webserver-prod-01.mydomain.com"`

- `hostname_contains` - A substring to match hostnames for which the risk acceptance applies.
  - **Type**: `string`
  - **Example**: `"worker"`

- `image` - The image name for which the vulnerability risk is being accepted. Wildcards can be used in both the beginning or the end of the name, but `*` alone is not allowed, nor is `*` in the middle.
  - **Type**: `string`
  - **Examples**: `"docker.io/library/nginx:1.21.0"`, `"*nginx:1.21.0"`, `"docker.io/library/nginx:*"`, `"*nginx*"`

- `package_name` - The name of the package for which the vulnerability risk is being accepted.
  - **Type**: `string`
  - **Example**: `"org.apache.logging.log4j:log4j-jcl"`

- `package_version` - The version of the package for which the vulnerability risk is being accepted.
  - **Type**: `string`
  - **Example**: `"2.14.1"`

- `rule_id` - The vulnerability scanning rule identifier to accept risks on.
  - **Type**: `string`
  - **Example**: `"12345"`

- `stages` - The stages where the risk acceptance applies. Possible values are `pipeline`, `runtime`, or both. It can also be an empty array.
  - **Type**: `list of strings`
  - **Example**: `["pipeline", "runtime"]`
  
#### Other required arguments

- `description` - A description providing details about the risk acceptance.
  - **Type**: `string`
  - **Example**: `"Accept risk for exact NGINX image due to mitigations applied"`

- `reason` - The reason for accepting the risk. Possible values are:
  - `RiskTransferred`
  - `RiskAvoided`
  - `RiskMitigated`
  - `RiskOwned`
  - `RiskNotRelevant`
  - `Custom`
  - **Type**: `string`
  - **Example**: `"RiskMitigated"`

### Optional arguments

- `expiration_date` - The date when the risk acceptance expires. The date must be in `YYYY-MM-DD` format.
  - **Type**: `string`
  - **Example**: `"2025-01-02"`

```

2025-01-03 13:10 UTC, airadier approved these changes

2025-01-16 15:01 UTC, filiptubic commented on package.nix
> +{
Why do we have all those .nix files?

2025-01-16 16:35 UTC, tembleking commented on package.nix
> +{
I removed all nix related files from this PR, let's continue this conversation later and get this one merged :+1:

2025-01-17 06:49 UTC, filiptubic approved these changes

2025-01-17 06:49 UTC, merged